version: "3.9"

services:
  elektro-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: sqlite3
    volumes:
      - ./data:/data
    restart: unless-stopped